# Generated by Django 4.1.7 on 2023-03-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_operationsaccount_bank_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_type', models.CharField(max_length=10)),
                ('date_received', models.DateField()),
            ],
        ),
    ]
