# Generated by Django 4.1.7 on 2023-03-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_operationsreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationsreceipt',
            name='receipt_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque')], max_length=10),
        ),
    ]
