# Generated by Django 4.1.7 on 2023-03-23 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_operationsreceipt_receipt_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationsreceipt',
            name='account_number',
        ),
        migrations.AddField(
            model_name='operationsreceipt',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.operationsaccount'),
        ),
    ]
