# Generated by Django 4.1.7 on 2023-03-23 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_remove_operationsreceipt_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationsreceipt',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounting.operationsaccount'),
        ),
    ]
