# Generated by Django 4.1.7 on 2023-03-24 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_budget_delete_operationstransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_budgeted', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.operationsaccount')),
                ('votehead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.votehead')),
            ],
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
