# Generated by Django 4.1.7 on 2023-03-24 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_operationsbudget_delete_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='votehead',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounting.operationsaccount'),
        ),
        migrations.AddField(
            model_name='votehead',
            name='account_number',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='votehead',
            name='account_type',
            field=models.CharField(choices=[('operations', 'Operations Account'), ('other', 'Other Account')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='votehead',
            name='amount_budgeted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='VoteHeadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_received', models.DateField()),
                ('votehead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.votehead')),
            ],
        ),
    ]
