# Generated by Django 4.1.7 on 2023-03-24 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_votehead_account_votehead_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque')], max_length=10)),
                ('approved_by', models.CharField(max_length=100)),
                ('votehead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.votehead')),
            ],
        ),
    ]
