# Generated by Django 4.1.7 on 2023-03-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_paymentvoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='voucher_number',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque')], default='cash', max_length=20),
        ),
    ]
