# Generated by Django 4.1.7 on 2023-03-24 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_cheque'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsChequeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_received', models.DateField()),
                ('account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounting.operationsaccount')),
            ],
        ),
        migrations.DeleteModel(
            name='OperationsReceipt',
        ),
    ]
