# Generated by Django 4.1.7 on 2023-03-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_operationsbankaccount_operationscashaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votehead',
            name='amount_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
