# Generated by Django 4.1.7 on 2023-03-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_votehead_amount_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='votehead',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
