# Generated by Django 4.1.7 on 2023-03-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_votehead_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsbankaccount',
            name='month_end_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
