# Generated by Django 4.1.7 on 2023-03-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_operationsbankaccount_month_end_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='payee_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
