# Generated by Django 4.1.7 on 2023-03-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_paymentvoucher_payee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationscashreceipt',
            name='received_from',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='operationschequereceipt',
            name='received_from',
            field=models.CharField(default='', max_length=100),
        ),
    ]
