# Generated by Django 4.1.7 on 2023-03-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_pettycash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pettycash',
            old_name='date',
            new_name='date_issued',
        ),
        migrations.RemoveField(
            model_name='pettycash',
            name='payee',
        ),
        migrations.AddField(
            model_name='pettycash',
            name='cheque_number',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='payee_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
