# Generated by Django 4.1.7 on 2023-03-28 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_rename_date_pettycash_date_issued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycash',
            name='operations_receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.operationscashreceipt'),
        ),
    ]
