# Generated by Django 4.1.7 on 2023-03-28 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_pettycash_operations_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pettycash',
            name='operations_receipt',
        ),
        migrations.AddField(
            model_name='pettycash',
            name='operations_account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounting.operationscashaccount'),
        ),
    ]
