# Generated by Django 4.1.7 on 2023-03-28 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_remove_pettycash_operations_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycash',
            name='operations_receipt',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounting.operationscashreceipt'),
        ),
        migrations.AlterField(
            model_name='operationscashreceipt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
