# Generated by Django 4.1.7 on 2023-03-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_pettycash_operations_receipt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pettycash',
            name='operations_receipt',
        ),
    ]
