# Generated by Django 4.1.7 on 2023-04-03 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_remove_pettycash_operations_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsbudget',
            name='cheque_receipt',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounting.operationschequereceipt'),
        ),
    ]
