# Generated by Django 4.1.7 on 2023-04-03 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_alter_operationsbudget_cheque_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationsbudget',
            name='cheque_receipt',
        ),
    ]
