# Generated by Django 4.1.7 on 2023-04-03 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_remove_operationsbudget_cheque_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsbudget',
            name='cheque_receipt',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounting.operationschequereceipt'),
        ),
    ]
